
socketio_address: "http://127.0.0.1:6000"

client_type: "BasicClient"
usecase:
  BearingUseCase:
    0:
      test_bearings: ["Bearing1_1", "Bearing1_2"]
    1: 
      test_bearings: ["Bearing2_1", "Bearing2_2"]
    2: 
      test_bearings: ["Bearing3_1", "Bearing3_2"]
  TurbofanUseCase:
    0:
      file_path: "../train.csv"
      file_id: 1
    1: 
      file_path: "../train.csv"
      file_id: 1
    2: 
      file_path: "../train.csv"
      file_id: 1

num_client_train_epochs: 3
learning_rate: null # null further to use default learning rate
DEBUG: False
